apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.envName }}
  labels:
    {{- range $key, $val := .Values.labels }}
    {{ $key }}: {{ $.Values.envName }}-{{ $val }}
    {{- end }}
  name: {{ .Values.envName }}-{{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
        {{- range $key, $val := .Values.labels }}
        {{ $key }}: {{ $.Values.envName }}-{{ $val }}
        {{- end }}
  template:
    metadata:
      labels:
        app: {{ .Values.envName }}-{{ .Values.name }}
    spec:
      containers:
      - image: {{ .Values.repoName }}/{{ .Values.imageName }}:v{{ .Values.BUILD_NUMBER }}
        name: {{ .Values.envName }}-{{ .Values.name }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        {{- range .Values.containerPorts }}
        - containerPort: {{ . }}
        {{- end }}
        resources: {}