apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    {{- range $key, $val := .Values.service.labels }}
    {{ $key }}: {{ $val }}
    {{- end }}
  name: {{ .Values.service.name }}
spec:
  ports:
  - name: {{ .Values.service.portName }}
    port: {{ .Values.service.portNumber }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPortNumber }}
  selector:
    {{- range $key, $val := .Values.labels }}
    {{ $key }}: {{ $val }}
    {{- end }}
  type: {{ .Values.service.serviceType }}
status:
  loadBalancer: {}