apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    {{- range $key, $val := .Values.service.labels }}
    {{ $key }}: {{ $val }}
    {{- end }}
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Values.service.name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: true
spec:
  ports:
  - name: {{ .Values.service.portName }}
    port: {{ .Values.service.portNumber }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPortNumber }}
  selector:
    {{- range $key, $val := .Values.labels }}
    {{ $key }}: {{ $val }}
    {{- end }}
  type: {{ .Values.service.serviceType }}
status:
  loadBalancer: {}