replicaCount: 1
name: "laravel-app"
labels:
  app: "laravel-app"
imagePullPolicy: "Always"
containerPorts:
  - 80
envName: "default"

service:
  name: "laravel-app-service"
  labels:
    app: "laravel-app"
  portName: "laravel-app-service-port"
  portNumber: 80
  protocol: "TCP"
  targetPortNumber: 80
  serviceType: NodePort

BUILD_NUMBER: 1
repoName: "ahmedlsheriff"
imageName: "laravel-app"