apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    app: "laravel-app-service"
  name: "laravel-app-service"
spec:
  replicas: 1
  selector:
    matchLabels:
        app: "laravel-app"
  template:
    metadata:
      labels:
        app: "laravel-app"
    spec:
      containers:
      - image: ahmedlsheriff/laravel-app:v${BUILD_NUMBER}
        name: "laravel-app"
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80